Break circular dependency in import graph (#413)
There was a circular dependency caused by this import chain:

`board.ts > runner.ts > serialization.ts > index.ts > board.ts` (a few
other paths too, but the `serialization.ts > index.ts` import is the
culprit in all cases).

This could cause errors like:

```
export class Board extends BoardRunner {
                           ^

ReferenceError: Cannot access 'BoardRunner' before initialization
```

because depending on where you enter that loop, you could end up
executing `board.js` before `runner.js`.

This fix is to import `MachineResult` and `TraversalMachine` directly
from their source files, instead of via `index.js.